import type { Trend, BlogPost } from '@/types/database';

export const fallbackTrends: Trend[] = [
  {
    id: 1,
    title: 'AI 마케팅 자동화의 미래',
    description: '2025년 AI 마케팅 자동화 트렌드와 중소기업 적용 전략을 살펴봅니다.',
    content: '<h2>AI 마케팅 자동화의 현재와 미래</h2><p>인공지능 기술의 발전으로 마케팅 자동화가 새로운 국면을 맞이하고 있습니다.</p>',
    emoji: '🤖',
    badge: 'HOT',
    date: '2025-02-15',
    tags: 'AI,마케팅,자동화',
    category: 'AI 트렌드',
    image: '',
    views: 245,
    is_published: true,
    sort_order: 1,
    created_at: '2025-02-15T00:00:00Z',
  },
  {
    id: 2,
    title: '챗GPT 활용 콘텐츠 마케팅',
    description: 'ChatGPT를 활용한 효과적인 콘텐츠 마케팅 전략과 실전 사례를 소개합니다.',
    content: '<h2>ChatGPT 콘텐츠 마케팅 가이드</h2><p>ChatGPT를 활용하여 고품질 마케팅 콘텐츠를 효율적으로 생산하는 방법을 알아봅니다.</p>',
    emoji: '💬',
    badge: 'NEW',
    date: '2025-02-10',
    tags: 'ChatGPT,콘텐츠,마케팅',
    category: 'AI 도구',
    image: '',
    views: 189,
    is_published: true,
    sort_order: 2,
    created_at: '2025-02-10T00:00:00Z',
  },
  {
    id: 3,
    title: '소셜미디어 AI 분석 도구',
    description: 'AI 기반 소셜미디어 분석 도구 Top 5와 활용 방법을 정리했습니다.',
    content: '<h2>소셜미디어 AI 분석 도구 Top 5</h2><p>데이터 기반의 소셜미디어 전략을 위한 AI 분석 도구를 소개합니다.</p>',
    emoji: '📊',
    badge: 'TREND',
    date: '2025-02-05',
    tags: '소셜미디어,분석,AI도구',
    category: 'AI 도구',
    image: '',
    views: 312,
    is_published: true,
    sort_order: 3,
    created_at: '2025-02-05T00:00:00Z',
  },
  {
    id: 4,
    title: 'AI 이미지 생성과 광고',
    description: 'Midjourney, DALL-E 등 AI 이미지 생성 도구를 광고에 활용하는 방법입니다.',
    content: '<h2>AI 이미지 생성 도구의 광고 활용</h2><p>AI가 만드는 이미지로 광고 효과를 극대화하는 전략을 알아봅니다.</p>',
    emoji: '🎨',
    badge: 'HOT',
    date: '2025-01-28',
    tags: 'AI이미지,광고,크리에이티브',
    category: 'AI 트렌드',
    image: '',
    views: 278,
    is_published: true,
    sort_order: 4,
    created_at: '2025-01-28T00:00:00Z',
  },
  {
    id: 5,
    title: 'AI SEO 최적화 전략',
    description: 'AI를 활용한 검색엔진 최적화 전략과 키워드 분석 방법을 다룹니다.',
    content: '<h2>AI 기반 SEO 최적화</h2><p>검색엔진 최적화에 AI 기술을 접목하여 더 효과적인 결과를 만들어봅니다.</p>',
    emoji: '🔍',
    badge: 'NEW',
    date: '2025-01-20',
    tags: 'SEO,AI,최적화',
    category: 'AI 마케팅',
    image: '',
    views: 156,
    is_published: true,
    sort_order: 5,
    created_at: '2025-01-20T00:00:00Z',
  },
];

export const fallbackBlogPosts: BlogPost[] = [
  {
    id: 1,
    title: '중소기업 AI 마케팅 시작 가이드',
    description: '중소기업이 AI 마케팅을 시작하기 위한 5단계 가이드를 제공합니다.',
    content: '<h2>AI 마케팅 시작 가이드</h2><p>중소기업도 쉽게 시작할 수 있는 AI 마케팅의 첫걸음을 안내합니다.</p>',
    emoji: '📘',
    category: '마케팅 가이드',
    category_class: 'guide',
    author: '김소장',
    read_time: '5분',
    image: '',
    date: '2025-02-14',
    tags: 'AI, 마케팅, 중소기업, 가이드',
    views: 189,
    likes: 45,
    is_published: true,
    sort_order: 1,
    created_at: '2025-02-14T00:00:00Z',
  },
  {
    id: 2,
    title: 'AI 광고 카피라이팅의 비밀',
    description: 'AI를 활용한 효과적인 광고 카피 작성법과 실전 노하우를 공개합니다.',
    content: '<h2>AI 광고 카피라이팅</h2><p>AI가 만드는 광고 카피의 효과와 활용법을 알아봅니다.</p>',
    emoji: '✍️',
    category: 'AI 활용법',
    category_class: 'ai',
    author: '김소장',
    read_time: '7분',
    image: '',
    date: '2025-02-09',
    tags: 'AI, 카피라이팅, 광고',
    views: 234,
    likes: 67,
    is_published: true,
    sort_order: 2,
    created_at: '2025-02-09T00:00:00Z',
  },
  {
    id: 3,
    title: '성공적인 SNS 마케팅 사례',
    description: 'AI를 활용한 SNS 마케팅 성공 사례 3가지를 분석합니다.',
    content: '<h2>SNS 마케팅 성공 사례</h2><p>실제 중소기업들의 AI 활용 SNS 마케팅 성공 스토리를 소개합니다.</p>',
    emoji: '📱',
    category: '성공 사례',
    category_class: 'case',
    author: '김소장',
    read_time: '6분',
    image: '',
    date: '2025-02-04',
    tags: 'SNS, 마케팅, 성공사례',
    views: 312,
    likes: 89,
    is_published: true,
    sort_order: 3,
    created_at: '2025-02-04T00:00:00Z',
  },
  {
    id: 4,
    title: '2025년 디지털 마케팅 트렌드',
    description: '올해 주목해야 할 디지털 마케팅 트렌드 Top 10을 소개합니다.',
    content: '<h2>2025 디지털 마케팅 트렌드</h2><p>AI, 개인화, 영상 마케팅 등 2025년의 핵심 트렌드를 살펴봅니다.</p>',
    emoji: '📈',
    category: '트렌드 분석',
    category_class: 'trend',
    author: '김소장',
    read_time: '8분',
    image: '',
    date: '2025-01-25',
    tags: '디지털마케팅, 트렌드, 2025',
    views: 456,
    likes: 123,
    is_published: true,
    sort_order: 4,
    created_at: '2025-01-25T00:00:00Z',
  },
  {
    id: 5,
    title: 'AI 마케팅 ROI 측정 방법',
    description: 'AI 마케팅의 투자 대비 효과를 정확하게 측정하는 방법을 알아봅니다.',
    content: '<h2>AI 마케팅 ROI 측정</h2><p>마케팅 투자 효과를 데이터로 증명하는 방법을 안내합니다.</p>',
    emoji: '💰',
    category: '마케팅 가이드',
    category_class: 'guide',
    author: '김소장',
    read_time: '6분',
    image: '',
    date: '2025-01-18',
    tags: 'ROI, AI마케팅, 성과측정',
    views: 178,
    likes: 34,
    is_published: true,
    sort_order: 5,
    created_at: '2025-01-18T00:00:00Z',
  },
];
